#pragma warning disable CS8618,CS8603
namespace GameFramework;
using CSharpToCpp.Utilities;
[CppInclude("GeometryScript/MeshPrimitiveFunctions.h")]
public partial class UGeometryScriptLibrary_MeshPrimitiveFunctions : UBlueprintFunctionLibrary {
// GeometryScriptLibrary_MeshPrimitiveFunctions
	public UObject AppendBox(UObject TargetMesh,FGeometryScriptPrimitiveOptions PrimitiveOptions,FTransform Transform,float DimensionX=100,float DimensionY=100,float DimensionZ=100,int StepsX=0,int StepsY=0,int StepsZ=0,EGeometryScriptPrimitiveOriginMode Origin=EGeometryScriptPrimitiveOriginMode,UObject Debug=nullptr,UObject ReturnValue) { return default; }
	public UObject AppendSphereLatLong(UObject TargetMesh,FGeometryScriptPrimitiveOptions PrimitiveOptions,FTransform Transform,float Radius=50,int StepsPhi=10,int StepsTheta=16,EGeometryScriptPrimitiveOriginMode Origin=EGeometryScriptPrimitiveOriginMode,UObject Debug=nullptr,UObject ReturnValue) { return default; }
	public UObject AppendSphereBox(UObject TargetMesh,FGeometryScriptPrimitiveOptions PrimitiveOptions,FTransform Transform,float Radius=50,int StepsX=6,int StepsY=6,int StepsZ=6,EGeometryScriptPrimitiveOriginMode Origin=EGeometryScriptPrimitiveOriginMode,UObject Debug=nullptr,UObject ReturnValue) { return default; }
	public UObject AppendCapsule(UObject TargetMesh,FGeometryScriptPrimitiveOptions PrimitiveOptions,FTransform Transform,float Radius=30,float LineLength=75,int HemisphereSteps=5,int CircleSteps=8,EGeometryScriptPrimitiveOriginMode Origin=EGeometryScriptPrimitiveOriginMode,UObject Debug=nullptr,UObject ReturnValue) { return default; }
	public UObject AppendCylinder(UObject TargetMesh,FGeometryScriptPrimitiveOptions PrimitiveOptions,FTransform Transform,float Radius=50,float Height=100,int RadialSteps=12,int HeightSteps=0,bool bCapped=true,EGeometryScriptPrimitiveOriginMode Origin=EGeometryScriptPrimitiveOriginMode,UObject Debug=nullptr,UObject ReturnValue) { return default; }
	public UObject AppendCone(UObject TargetMesh,FGeometryScriptPrimitiveOptions PrimitiveOptions,FTransform Transform,float BaseRadius=50,float TopRadius=5,float Height=100,int RadialSteps=12,int HeightSteps=4,bool bCapped=true,EGeometryScriptPrimitiveOriginMode Origin=EGeometryScriptPrimitiveOriginMode,UObject Debug=nullptr,UObject ReturnValue) { return default; }
	public UObject AppendTorus(UObject TargetMesh,FGeometryScriptPrimitiveOptions PrimitiveOptions,FTransform Transform,FGeometryScriptRevolveOptions RevolveOptions,float MajorRadius=50,float MinorRadius=25,int MajorSteps=16,int MinorSteps=8,EGeometryScriptPrimitiveOriginMode Origin=EGeometryScriptPrimitiveOriginMode,UObject Debug=nullptr,UObject ReturnValue) { return default; }
	public UObject AppendRevolvePolygon(UObject TargetMesh,FGeometryScriptPrimitiveOptions PrimitiveOptions,FTransform Transform,TArray<FVector2D> PolygonVertices,FGeometryScriptRevolveOptions RevolveOptions,float Radius=100,int Steps=8,UObject Debug=nullptr,UObject ReturnValue) { return default; }
	public UObject AppendSpiralRevolvePolygon(UObject TargetMesh,FGeometryScriptPrimitiveOptions PrimitiveOptions,FTransform Transform,TArray<FVector2D> PolygonVertices,FGeometryScriptRevolveOptions RevolveOptions,float Radius=100,int Steps=18,float RisePerRevolution=50,UObject Debug=nullptr,UObject ReturnValue) { return default; }
	public UObject AppendRevolvePath(UObject TargetMesh,FGeometryScriptPrimitiveOptions PrimitiveOptions,FTransform Transform,TArray<FVector2D> PathVertices,FGeometryScriptRevolveOptions RevolveOptions,int Steps=8,bool bCapped=true,UObject Debug=nullptr,UObject ReturnValue) { return default; }
	public UObject AppendSweepPolyline(UObject TargetMesh,FGeometryScriptPrimitiveOptions PrimitiveOptions,FTransform Transform,TArray<FVector2D> PolylineVertices,TArray<FTransform> SweepPath,TArray<float> PolylineTexParamU,TArray<float> SweepPathTexParamV,bool bLoop=false,float StartScale=1.0f,float EndScale=1.0f,float RotationAngleDeg=0.0f,UObject Debug=nullptr,UObject ReturnValue) { return default; }
	public UObject AppendSimpleExtrudePolygon(UObject TargetMesh,FGeometryScriptPrimitiveOptions PrimitiveOptions,FTransform Transform,TArray<FVector2D> PolygonVertices,float Height=100,int HeightSteps=0,bool bCapped=true,EGeometryScriptPrimitiveOriginMode Origin=EGeometryScriptPrimitiveOriginMode,UObject Debug=nullptr,UObject ReturnValue) { return default; }
	public UObject AppendSimpleSweptPolygon(UObject TargetMesh,FGeometryScriptPrimitiveOptions PrimitiveOptions,FTransform Transform,TArray<FVector2D> PolygonVertices,TArray<FVector> SweepPath,bool bLoop=false,bool bCapped=true,float StartScale=1.0f,float EndScale=1.0f,UObject Debug=nullptr,UObject ReturnValue) { return default; }
	public UObject AppendSweepPolygon(UObject TargetMesh,FGeometryScriptPrimitiveOptions PrimitiveOptions,FTransform Transform,TArray<FVector2D> PolygonVertices,TArray<FTransform> SweepPath,bool bLoop=false,bool bCapped=true,float StartScale=1.0f,float EndScale=1.0f,float RotationAngleDeg=0.0f,UObject Debug=nullptr,UObject ReturnValue) { return default; }
	public UObject AppendRectangleXY(UObject TargetMesh,FGeometryScriptPrimitiveOptions PrimitiveOptions,FTransform Transform,float DimensionX=100,float DimensionY=100,int StepsWidth=0,int StepsHeight=0,UObject Debug=nullptr,UObject ReturnValue) { return default; }
	public UObject AppendRoundRectangleXY(UObject TargetMesh,FGeometryScriptPrimitiveOptions PrimitiveOptions,FTransform Transform,float DimensionX=100,float DimensionY=100,float CornerRadius=5,int StepsWidth=0,int StepsHeight=0,int StepsRound=4,UObject Debug=nullptr,UObject ReturnValue) { return default; }
	public UObject AppendDisc(UObject TargetMesh,FGeometryScriptPrimitiveOptions PrimitiveOptions,FTransform Transform,float Radius=50,int AngleSteps=16,int SpokeSteps=0,float StartAngle=0,float EndAngle=360,float HoleRadius=0,UObject Debug=nullptr,UObject ReturnValue) { return default; }
	public UObject AppendTriangulatedPolygon(UObject TargetMesh,FGeometryScriptPrimitiveOptions PrimitiveOptions,FTransform Transform,TArray<FVector2D> PolygonVertices,bool bAllowSelfIntersections=true,UObject Debug=nullptr,UObject ReturnValue) { return default; }
	public UObject AppendLinearStairs(UObject TargetMesh,FGeometryScriptPrimitiveOptions PrimitiveOptions,FTransform Transform,float StepWidth=100.0f,float StepHeight=20.0f,float StepDepth=30.0f,int NumSteps=8,bool bFloating=false,UObject Debug=nullptr,UObject ReturnValue) { return default; }
	public UObject AppendCurvedStairs(UObject TargetMesh,FGeometryScriptPrimitiveOptions PrimitiveOptions,FTransform Transform,float StepWidth=100.0f,float StepHeight=20.0f,float InnerRadius=150.0f,float CurveAngle=90.0f,int NumSteps=8,bool bFloating=false,UObject Debug=nullptr,UObject ReturnValue) { return default; }
	public UObject AppendVoronoiDiagram2D(UObject TargetMesh,FGeometryScriptPrimitiveOptions PrimitiveOptions,FTransform Transform,TArray<FVector2D> VoronoiSites,FGeometryScriptVoronoiOptions VoronoiOptions,UObject Debug=nullptr,UObject ReturnValue) { return default; }
	public UObject AppendRectangle_Compatibility_5_0(UObject TargetMesh,FGeometryScriptPrimitiveOptions PrimitiveOptions,FTransform Transform,float DimensionX=100,float DimensionY=100,int StepsWidth=0,int StepsHeight=0,UObject Debug=nullptr,UObject ReturnValue) { return default; }
	public UObject AppendRoundRectangle_Compatibility_5_0(UObject TargetMesh,FGeometryScriptPrimitiveOptions PrimitiveOptions,FTransform Transform,float DimensionX=100,float DimensionY=100,float CornerRadius=5,int StepsWidth=0,int StepsHeight=0,int StepsRound=4,UObject Debug=nullptr,UObject ReturnValue) { return default; }
}
