#pragma warning disable CS8618,CS8603
namespace GameFramework;
using CSharpToCpp.Utilities;
[CppInclude("EdGraph/EdGraphPin.h")]
public partial class UEdGraphPin_Deprecated : UObject {
// EdGraphPin_Deprecated
	public sbyte PinName;
	public sbyte PinFriendlyName;
	public sbyte PinToolTip;
	public byte Direction;
	public FEdGraphPinType PinType;
	public sbyte DefaultValue;
	public sbyte AutogeneratedDefaultValue;
	public UObject DefaultObject;
	public sbyte DefaultTextValue;
	public TArray<UEdGraphPin_Deprecated> LinkedTo;
	public TArray<UEdGraphPin_Deprecated> SubPins;
	public UEdGraphPin_Deprecated ParentPin;
	public UEdGraphPin_Deprecated ReferencePassThroughConnection;
	public bool bHidden;
	public bool bNotConnectable;
	public bool bDefaultValueIsReadOnly;
	public bool bDefaultValueIsIgnored;
	public bool bAdvancedView;
	public bool bDisplayAsMutableRef;
	public FGuid PersistentGuid;
}
