#pragma warning disable CS8618,CS8603
namespace GameFramework;
using CSharpToCpp.Utilities;
[CppInclude("Engine/SCS_Node.h")]
public partial class USCS_Node : UObject {
// SCS_Node
	public UClass ComponentClass;
	public UActorComponent ComponentTemplate;
	public FBlueprintCookedComponentInstancingData CookedComponentInstancingData;
	public sbyte CategoryName;
	public sbyte AttachToName;
	public sbyte ParentComponentOrVariableName;
	public sbyte ParentComponentOwnerClassName;
	public bool bIsParentComponentNative;
	public TArray<USCS_Node> ChildNodes;
	public TArray<FBPVariableMetaDataEntry> MetaDataArray;
	public FGuid VariableGuid;
	public bool bIsNative_DEPRECATED;
	public sbyte NativeComponentName_DEPRECATED;
	public bool bVariableNameAutoGenerated_DEPRECATED;
	public sbyte InternalVariableName;
}
